import { useMemo,useRef,useState } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'
import { Activity,Braces,ChevronDown,CircleDot,Clock3,Copy,FileClock,FolderOpen,GitBranch,MonitorSmartphone,Pause,Play,Plus,Radio,Save,Search,Settings,Square,Trash2,Wifi,WifiOff,X } from 'lucide-react'
import type { EventFlow,LogEntry } from '@shared/types'
import { send,useAppStore } from './store'

const formatTime=(value:string)=>{const d=new Date(value);return Number.isNaN(d.getTime())?value.split(' ').at(-1)??value:d.toLocaleTimeString([],{hour12:false})+'.'+String(d.getMilliseconds()).padStart(3,'0')}
const size=(bytes=0)=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`
function Button({children,onClick,disabled,kind='secondary',title}:{children:React.ReactNode;onClick?:()=>void;disabled?:boolean;kind?:'primary'|'secondary'|'purple'|'danger';title?:string}){return <button className={`btn ${kind}`} onClick={onClick} disabled={disabled} title={title}>{children}</button>}

export function App(){const s=useAppStore();const [query,setQuery]=useState('');const [tag,setTag]=useState('all');const [dialog,setDialog]=useState<'record'|'flow'|'confirm-session'|null>(null);const [editingFlow,setEditingFlow]=useState<EventFlow>();const [pendingSession,setPendingSession]=useState<string>();const tags=useMemo(()=>[...new Set(s.logs.map(x=>x.eventTag??x.tag))].sort(),[s.logs]);const filtered=useMemo(()=>{const q=query.toLowerCase();return s.logs.filter(x=>(tag==='all'||(x.eventTag??x.tag)===tag)&&(!q||x.raw.toLowerCase().includes(q)||x.eventName?.toLowerCase().includes(q)||JSON.stringify(x.message).toLowerCase().includes(q)))},[s.logs,query,tag])
 const openSession=(id:string)=>{if(s.streamState!=='stopped'){setPendingSession(id);setDialog('confirm-session')}else send({type:'session:open',sessionId:id})}
 return <div className="app-shell"><Header/><div className="workspace"><Sidebar openSession={openSession} onNewFlow={()=>{setEditingFlow(undefined);setDialog('flow')}} onEditFlow={flow=>{setEditingFlow(flow);setDialog('flow')}}/><main className="main"><div className="toolbar"><div className="device-select"><MonitorSmartphone size={15}/><select value={s.selectedDeviceId??''} onChange={e=>s.set({selectedDeviceId:e.target.value||undefined})}><option value="">Select device…</option>{s.devices.map(d=><option key={d.id} value={d.id} disabled={d.status!=='online'}>{d.model??d.id} · {d.status}</option>)}</select><ChevronDown size={13}/></div>{s.streamState==='running'?<Button kind="primary" onClick={()=>send({type:'stream:pause'})}><Pause/> Pause</Button>:<Button kind="primary" disabled={!s.selectedDeviceId&&s.streamState==='stopped'} onClick={()=>send({type:s.streamState==='paused'?'stream:resume':'stream:start',...(s.streamState==='stopped'?{deviceId:s.selectedDeviceId!}: {})} as never)}><Play/> Play</Button>}<Button disabled={s.streamState==='stopped'} onClick={()=>send({type:'stream:stop'})}><Square/> Stop</Button><Button onClick={()=>send({type:'stream:clear'})}><Trash2/> Clear</Button><Button kind="purple" disabled={s.streamState==='stopped'} onClick={()=>s.recordingState==='recording'?setDialog('record'):send({type:'recording:start'})}>{s.recordingState==='recording'?<><span className="record-dot"/> Stop recording</>:<><CircleDot/> Record session</>}</Button><div className="live-stat"><span className={`pulse ${s.streamState}`}/>{s.streamState==='running'?'Live':s.streamState} <b>{s.logs.length.toLocaleString()}</b></div></div>
 <div className="searchbar"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events (eventName, tag, or text…)"/>{query&&<button onClick={()=>setQuery('')}><X size={14}/></button>}</div><select value={tag} onChange={e=>setTag(e.target.value)}><option value="all">All tags</option>{tags.map(t=><option key={t}>{t}</option>)}</select><span className="result-count">{filtered.length.toLocaleString()} events</span></div>
 <div className="content"><LogTable logs={filtered}/><Details/></div></main></div><StatusBar/>{s.error&&<div className="toast"><span>{s.error}</span><button onClick={()=>s.set({error:undefined})}><X size={15}/></button></div>}{dialog==='record'&&<NameDialog title="Save recorded session" label="Session name" placeholder="Onboarding Debug" confirm="Save session" onCancel={()=>setDialog(null)} onConfirm={name=>{send({type:'recording:stop',name});setDialog(null)}}/>}{dialog==='flow'&&<FlowDialog existing={editingFlow} onClose={()=>setDialog(null)}/>} {dialog==='confirm-session'&&<ConfirmDialog onCancel={()=>setDialog(null)} onConfirm={()=>{send({type:'session:open',sessionId:pendingSession!});setDialog(null)}}/>}</div>}

function Header(){const s=useAppStore();return <header><div className="brand"><div className="logo"><Activity/></div><div><strong>EventDeck</strong><span>Stream. Validate. Debug.</span></div></div><div className="header-meta"><span className="version">v0.1.0</span><span className={s.connected?'good':'bad'}>{s.connected?<Wifi/>:<WifiOff/>}{s.connected?'Server connected':'Reconnecting'}</span><code>{location.host}</code><button aria-label="Settings"><Settings/></button></div></header>}
function Sidebar({openSession,onNewFlow,onEditFlow}:{openSession:(id:string)=>void;onNewFlow:()=>void;onEditFlow:(flow:EventFlow)=>void}){const s=useAppStore();return <aside><SectionTitle icon={<MonitorSmartphone/>} text="Connected devices"/><div className="side-list">{!s.adbAvailable?<Empty text="ADB is not installed or unavailable."/>:s.devices.length===0?<Empty text="No Android devices found."/>:s.devices.map(d=><button key={d.id} className={`side-item ${s.selectedDeviceId===d.id?'active':''}`} onClick={()=>s.set({selectedDeviceId:d.id,view:'live'})}><span className={`device-dot ${d.status}`}/><span><b>{d.model??d.id}</b><small>{d.id}</small></span><em>{d.status}</em></button>)}</div><SectionTitle icon={<FileClock/>} text="Recorded sessions"/><div className="side-list sessions">{s.sessions.length===0?<Empty text="Recorded sessions appear here."/>:s.sessions.map(x=><div key={x.id} className={`side-action ${s.activeSession?.id===x.id?'active':''}`}><button onClick={()=>openSession(x.id)}><FileClock/><span><b>{x.name}</b><small>{x.totalLogs.toLocaleString()} logs · {size(x.sizeBytes)}</small></span></button><button title="Delete session" onClick={()=>confirm(`Delete “${x.name}”?`)&&send({type:'session:delete',sessionId:x.id})}><Trash2/></button></div>)}</div><div className="section-row"><SectionTitle icon={<GitBranch/>} text="Event flows"/><button className="icon-btn" onClick={onNewFlow} title="Create flow"><Plus/></button></div><div className="side-list flows">{s.flows.length===0?<Empty text="Define your first expected flow."/>:s.flows.map(flow=><div className="flow-card" key={flow.id}><div className="flow-main"><button onClick={()=>send({type:'flow:start-validation',flowId:flow.id})}><GitBranch/><span><b>{flow.name}</b><small>{flow.events.length} expected events</small></span><Play/></button><button title="Edit flow" onClick={()=>onEditFlow(flow)}><Settings/></button><button title="Delete flow" onClick={()=>confirm(`Delete “${flow.name}”?`)&&send({type:'flow:delete',flowId:flow.id})}><Trash2/></button></div>{s.validation?.flowId===flow.id&&<div className="flow-progress"><span style={{width:`${s.validation.matchedCount/Math.max(1,s.validation.totalCount)*100}%`}}/><small>{s.validation.matchedCount} / {s.validation.totalCount} found</small></div>}</div>)}</div></aside>}
function SectionTitle({icon,text}:{icon:React.ReactNode;text:string}){return <div className="section-title">{icon}<span>{text}</span></div>}function Empty({text}:{text:string}){return <div className="empty-small">{text}</div>}

function LogTable({logs}:{logs:LogEntry[]}){const parent=useRef<HTMLDivElement>(null);const virtual=useVirtualizer({count:logs.length,getScrollElement:()=>parent.current,estimateSize:()=>36,overscan:12});return <section className="table-panel"><div className="table-head"><span>#</span><span>Timestamp</span><span>Tag</span><span>Event</span><span>Message</span></div><div className="table-scroll" ref={parent}>{logs.length===0?<div className="empty-main"><div><Radio/><span/></div><h2>{useAppStore.getState().streamState==='stopped'?'Ready to capture events':'Listening for events…'}</h2><p>Select a connected device and press Play to stream tagged JSON events from Logcat.</p></div>:<div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(row=>{const log=logs[row.index];return <LogRow key={log.id} log={log} style={{transform:`translateY(${row.start}px)`}}/>})}</div>}</div></section>}
function LogRow({log,style}:{log:LogEntry;style:React.CSSProperties}){const s=useAppStore();const msg=typeof log.message==='string'?log.message:JSON.stringify(log.message);return <button className={`log-row ${s.selectedLog?.id===log.id?'selected':''}`} style={style} onClick={()=>s.set({selectedLog:log})}><span className="num">{log.id}</span><span>{formatTime(log.timestamp)}</span><span><i className={`tag tag-${(log.eventTag??log.tag).toLowerCase()}`}>{log.eventTag??log.tag}</i></span><span className="event-name">{log.eventName??'—'}</span><code>{msg}</code></button>}
function Details(){const log=useAppStore(x=>x.selectedLog);const [tab,setTab]=useState<'json'|'formatted'|'raw'>('json');if(!log)return <section className="details empty-details"><Braces/><h3>Event details</h3><p>Select an event to inspect its payload, context, and raw Logcat entry.</p></section>;const obj=typeof log.message==='object'?log.message:{};return <section className="details"><div className="details-title"><span><small>EVENT #{log.id}</small><h2>{log.eventName??'Log entry'}</h2></span><i className={`tag tag-${(log.eventTag??log.tag).toLowerCase()}`}>{log.eventTag??log.tag}</i></div><div className="quick"><span><Clock3/> {formatTime(log.timestamp)}</span><span><MonitorSmartphone/> {log.deviceId}</span></div><div className="tabs">{(['json','formatted','raw'] as const).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='json'&&<div className="code-wrap"><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(log.message,null,2))}><Copy/> Copy JSON</button><pre>{JSON.stringify(log.message,null,2)}</pre></div>}{tab==='formatted'&&<div className="fields">{Object.entries(obj).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><code>{typeof v==='object'?JSON.stringify(v,null,2):String(v)}</code></div>)}</div>}{tab==='raw'&&<pre className="raw">{log.raw}</pre>}</section>}
function StatusBar(){const s=useAppStore();return <footer><span><Activity/> Virtualized rendering</span><span>{s.logs.length.toLocaleString()} events loaded</span><span className={s.connected?'good':'bad'}>{s.connected?'WebSocket connected':'WebSocket disconnected'}</span><span>Device: {s.devices.find(x=>x.id===s.selectedDeviceId)?.model??'None'}</span><span>Server: {location.host}</span></footer>}

function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal">{children}</div></div>}
function NameDialog({title,label,placeholder,confirm,onCancel,onConfirm}:{title:string;label:string;placeholder:string;confirm:string;onCancel:()=>void;onConfirm:(x:string)=>void}){const [name,setName]=useState('');return <Modal onClose={onCancel}><h2>{title}</h2><p>Name it so you can find this capture later.</p><label>{label}<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={placeholder} onKeyDown={e=>e.key==='Enter'&&name.trim()&&onConfirm(name)}/></label><div className="modal-actions"><Button onClick={onCancel}>Cancel</Button><Button kind="purple" disabled={!name.trim()} onClick={()=>onConfirm(name)}><Save/> {confirm}</Button></div></Modal>}
function ConfirmDialog({onCancel,onConfirm}:{onCancel:()=>void;onConfirm:()=>void}){return <Modal onClose={onCancel}><div className="modal-icon"><FolderOpen/></div><h2>Stop the current live stream?</h2><p>Opening a recorded session will stop Logcat streaming. Your saved recordings won’t be affected.</p><div className="modal-actions"><Button onClick={onCancel}>Cancel</Button><Button kind="purple" onClick={onConfirm}>Continue</Button></div></Modal>}
function FlowDialog({existing,onClose}:{existing?:EventFlow;onClose:()=>void}){const [name,setName]=useState(existing?.name??'');const [events,setEvents]=useState(existing?.events.map(x=>x.eventName).join('\n')??'');const save=()=>{const now=new Date().toISOString();const previous=new Map(existing?.events.map(x=>[x.eventName,x.id]));const flow:EventFlow={id:existing?.id??crypto.randomUUID(),name:name.trim(),description:existing?.description,validationMode:'presence',events:events.split(/\n|,/).map(x=>x.trim()).filter(Boolean).map(eventName=>({id:previous.get(eventName)??crypto.randomUUID(),eventName})),createdAt:existing?.createdAt??now,updatedAt:now};send({type:'flow:save',flow});onClose()};return <Modal onClose={onClose}><h2>{existing?'Edit event flow':'Create event flow'}</h2><p>List the events you expect to find in a live stream.</p><label>Flow name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Signup Flow"/></label><label>Expected events<textarea rows={7} value={events} onChange={e=>setEvents(e.target.value)} placeholder={'signup_screen_view\nphone_entered\notp_requested\nsignup_completed'}/><small>One event name per line</small></label><div className="modal-actions"><Button onClick={onClose}>Cancel</Button><Button kind="purple" disabled={!name.trim()||!events.trim()} onClick={save}><Save/> {existing?'Save changes':'Create flow'}</Button></div></Modal>}
