import { create } from 'zustand'
import type { ClientMessage,Device,EventFlow,FlowValidationResult,LogEntry,RecordedSession,RecordingState,ServerMessage,StreamState } from '@shared/types'
export const MAX_LIVE_LOGS=250_000
type View='live'|'session'|'flows'
interface State{connected:boolean;adbAvailable:boolean;devices:Device[];selectedDeviceId?:string;sessions:RecordedSession[];flows:EventFlow[];logs:LogEntry[];streamState:StreamState;recordingState:RecordingState;validation?:FlowValidationResult;selectedLog?:LogEntry;view:View;activeSession?:RecordedSession;error?:string;set:(patch:Partial<State>)=>void;receive:(message:ServerMessage)=>void}
export const useAppStore=create<State>((set)=>({connected:false,adbAvailable:false,devices:[],sessions:[],flows:[],logs:[],streamState:'stopped',recordingState:'idle',view:'live',set,receive:(m)=>set(s=>{switch(m.type){case'bootstrap':return{devices:m.devices,sessions:m.sessions,flows:m.flows,streamState:m.streamState,recordingState:m.recordingState,adbAvailable:m.adbAvailable};case'devices:update':return{devices:m.devices};case'logs:batch':return{logs:[...s.logs,...m.logs].slice(-MAX_LIVE_LOGS)};case'logs:clear':return{logs:[],selectedLog:undefined};case'stream:state':return{streamState:m.state};case'recording:state':return{recordingState:m.state};case'session:saved':return{};case'session:loaded':return{logs:m.logs,activeSession:m.session,view:'session',selectedLog:undefined};case'sessions:update':return{sessions:m.sessions};case'flows:update':return{flows:m.flows};case'flow:validation-update':return{validation:m.result};case'error':return{error:m.message};default:return{}}})}))
let socket:WebSocket|undefined
export function connect(){const protocol=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${protocol}://${location.host}/ws`);socket.onopen=()=>useAppStore.getState().set({connected:true,error:undefined});socket.onclose=()=>{useAppStore.getState().set({connected:false});setTimeout(connect,1500)};socket.onmessage=e=>useAppStore.getState().receive(JSON.parse(e.data))}
export function send(message:ClientMessage){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(message));else useAppStore.getState().set({error:'WebSocket is disconnected.'})}
